#:schema ./schemas/ruff-permissive.schema.json

target-version = "py311"
line-length = 100
fix = true
extend-exclude = [
	"__archive__",
	".venv",
	".uv-cache",
	".ruff_cache",
	".pytest_cache",
	"__pycache__",
]

[lint]
select = [
	"E",   # pycodestyle errors
	"W",   # pycodestyle warnings
	"F",   # pyflakes
	"D",   # pydocstyle
	"I",   # isort
	"UP",  # pyupgrade
	"ANN",
	"B",   # flake8-bugbear
]
ignore = ["D107", "D203", "D213"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"tests/**" = ["D", "ANN"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
